// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('google').directive('groupLocator', function($parse, GoogleMap, $rootScope) {
    return {
      restrict: 'EC',
      template: "<div class=\"map-canvas\"></div>",
      link: function($scope, $elem, attr) {
        var genContent, gmap, plotGroups;
        if (attr.height) {
          $elem.css('height', attr.height);
        }
        gmap = new GoogleMap($elem[0], {
          zoom: parseInt(attr.zoom, 10),
          center: new google.maps.LatLng(51.50471558011393, -0.172)
        });
        window.map = gmap.map;
        if (attr.mapHandle != null) {
          $parse(attr.mapHandle).assign($scope, gmap);
        }
        genContent = function(group) {
          return " <div id=\"content\">\n  <h4>" + group.name + "</h4>\n</div>";
        };
        plotGroups = function(groups) {
          var g, id, ll, _results;
          console.log('Plotting');
          _results = [];
          for (id in groups) {
            g = groups[id];
            ll = new google.maps.LatLng(g.latlng.d, g.latlng.e);
            _results.push(g.marker = gmap.moveMarker(g.marker, ll, {
              drag: false,
              recenter: false,
              content: genContent(g)
            }));
          }
          return _results;
        };
        return $scope.$watchCollection(attr.groups, function(groups, _old) {
          console.log('Detected change');
          console.log(groups);
          return setTimeout((function() {
            return plotGroups(groups);
          }), 10);
        });
      }
    };
  });

}).call(this);
